vim ./wfp_state_based/tc_interleavedparallelrouting.rb
vim ./wfp_state_based/tc_deferredchoice.rb
vim ./wfp_iteration/tc_structuredloop.rb
vim ./wfp_adv_branching
vim ./wfp_adv_branching/tc_multichoice_structuredsynchronizingmerge.rb
vim ./wfp_adv_branching/tc_generalsynchronizingmerge.rb
vim ./wfp_adv_branching/tc_localsynchronizingmerge.rb
vim ./wfp_adv_branching/tc_threadmerge.rb
vim ./wfp_adv_branching/tc_generalizedjoin.rb
vim ./wfp_adv_branching/tc_threadsplit.rb
vim ./wfp_adv_branching/tc_multimerge.rb
vim ./wfp_adv_branching/tc_structured_discriminator.rb
vim ./wfp_adv_branching/tc_structured_partial_join.rb
vim ./basic/tc_codereplace.rb
vim ./basic/tc_data.rb
vim ./basic/tc_handler.rb
vim ./basic/tc_parallel.rb
vim ./basic/tc_search.rb
vim ./basic/tc_endpoint.rb
vim ./basic/tc_wf_control.rb
vim ./basic/tc_choose.rb
vim ./basic/tc_state.rb
vim ./wfp_basic/tc_exclusivechoice_simplemerge.rb
vim ./wfp_basic/tc_sequence.rb
vim ./wfp_basic/tc_parallelsplit_synchronization.rb
